use_frameworks!

target 'fcm-channel-ios_Example' do
  pod 'fcm-channel-ios', :path => '../'

  target 'fcm-channel-ios_Tests' do
    inherit! :search_paths

    pod 'ISScrollViewPageSwift', :git => 'https://github.com/ilhasoft/ISScrollViewPageSwift', :branch => 'master'

  end
end
